DROP DATABASE IF EXISTS Xwrite_your_best_database;

CREATE DATABASE write_your_best_database;

use write_your_best_database;

SET FOREIGN_KEY_CHECKS=0
;

DROP TABLE IF EXISTS `ACCOUNTS` CASCADE
;

DROP TABLE IF EXISTS `BAN_HISTORY` CASCADE
;

DROP TABLE IF EXISTS `COMPOSITIONS` CASCADE
;

DROP TABLE IF EXISTS `FOLLOWINGS` CASCADE
;

DROP TABLE IF EXISTS `PAYMENT_HISTORY` CASCADE
;

DROP TABLE IF EXISTS `THEMES` CASCADE
;

CREATE TABLE `ACCOUNTS`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`CREATION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`TYPE` CHAR(10) NOT NULL,
	`NICKNAME` VARCHAR(30) NOT NULL,
	`PASSWORD` VARCHAR(30) NOT NULL,
	`EMAIL` VARCHAR(30) NOT NULL,
	CONSTRAINT `PK_ACCOUNTS` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `BAN_HISTORY`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`ADMIN_ID` INTEGER NOT NULL,
	`USER_ID` INTEGER NOT NULL,
	`BAN_DATE` DATETIME NOT NULL,
	`UNBAN_DATE` DATETIME NOT NULL,
	CONSTRAINT `PK_BAN_HISTORY` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `COMPOSITIONS`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`THEME_ID` INTEGER NOT NULL,
	`AUTHOR_ID` INTEGER NOT NULL,
	`CREATION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`BODY` TEXT NOT NULL,
	CONSTRAINT `PK_COMPOSITIONS` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `FOLLOWINGS`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`USER_ID` INTEGER NOT NULL,
	`FRIEND_ID` INTEGER NOT NULL,
	CONSTRAINT `PK_FOLLOWINGS` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `PAYMENT_HISTORY`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`USER_ID` INTEGER NOT NULL,
	`AMOUNT` INTEGER NOT NULL,
	`ENABLE_DATE` DATETIME NOT NULL,
	`DISABLE_DATE` DATETIME NOT NULL,
	CONSTRAINT `PK_PAYMENT_HISTORY` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `THEMES`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`ADMIN_ID` INTEGER NOT NULL,
	`CREATION_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`BODY` TEXT NOT NULL,
	CONSTRAINT `PK_THEMES` PRIMARY KEY (`ID` ASC)
)
;

ALTER TABLE `BAN_HISTORY` 
 ADD INDEX `IXFK_BAN_HISTORY_ACCOUNTS` (`ADMIN_ID` ASC)
;

ALTER TABLE `BAN_HISTORY` 
 ADD INDEX `IXFK_BAN_HISTORY_ACCOUNTS_02` (`USER_ID` ASC)
;

ALTER TABLE `COMPOSITIONS` 
 ADD INDEX `IXFK_COMPOSITIONS_ACCOUNTS` (`AUTHOR_ID` ASC)
;

ALTER TABLE `COMPOSITIONS` 
 ADD INDEX `IXFK_COMPOSITIONS_THEMES` (`THEME_ID` ASC)
;

ALTER TABLE `FOLLOWINGS` 
 ADD INDEX `IXFK_FOLLOWINGS_ACCOUNTS` (`USER_ID` ASC)
;

ALTER TABLE `FOLLOWINGS` 
 ADD INDEX `IXFK_FOLLOWINGS_ACCOUNTS_02` (`FRIEND_ID` ASC)
;

ALTER TABLE `PAYMENT_HISTORY` 
 ADD INDEX `IXFK_PAYMENT_HISTORY_ACCOUNTS` (`USER_ID` ASC)
;

ALTER TABLE `THEMES` 
 ADD INDEX `IXFK_THEMES_ACCOUNTS` (`ADMIN_ID` ASC)
;

ALTER TABLE `ACCOUNTS` 
 ADD CONSTRAINT `NICKNAME_UNIQUE` UNIQUE (`NICKNAME` ASC)
;

ALTER TABLE `BAN_HISTORY` 
 ADD CONSTRAINT `FK_BAN_HISTORY_ACCOUNTS`
	FOREIGN KEY (`ADMIN_ID`) REFERENCES `ACCOUNTS` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `BAN_HISTORY` 
 ADD CONSTRAINT `FK_BAN_HISTORY_ACCOUNTS_02`
	FOREIGN KEY (`USER_ID`) REFERENCES `ACCOUNTS` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `COMPOSITIONS` 
 ADD CONSTRAINT `FK_COMPOSITIONS_ACCOUNTS`
	FOREIGN KEY (`AUTHOR_ID`) REFERENCES `ACCOUNTS` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `COMPOSITIONS` 
 ADD CONSTRAINT `FK_COMPOSITIONS_THEMES`
	FOREIGN KEY (`THEME_ID`) REFERENCES `THEMES` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FOLLOWINGS` 
 ADD CONSTRAINT `FK_FOLLOWINGS_ACCOUNTS`
	FOREIGN KEY (`USER_ID`) REFERENCES `ACCOUNTS` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `FOLLOWINGS` 
 ADD CONSTRAINT `FK_FOLLOWINGS_ACCOUNTS_02`
	FOREIGN KEY (`FRIEND_ID`) REFERENCES `ACCOUNTS` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `PAYMENT_HISTORY` 
 ADD CONSTRAINT `FK_PAYMENT_HISTORY_ACCOUNTS`
	FOREIGN KEY (`USER_ID`) REFERENCES `ACCOUNTS` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `THEMES` 
 ADD CONSTRAINT `FK_THEMES_ACCOUNTS`
	FOREIGN KEY (`ADMIN_ID`) REFERENCES `ACCOUNTS` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;

